In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df=pd.read_excel("/content/drive/MyDrive/pluralcode data science/ZENITH_BANK_PEJU.xlsx")

In [ ]:
df

,DATE,DESCRIPTION,DEPOSITS,WITHDRAWALS,BALANCE
0,NaN,Opening Balance,28097710.09,0.00,28097710.09
1,01/07/2026,307510463////4772285//DEWLL INTERNATIONAL LOGI...,NaN,-2513307.00,25584403.09
2,01/07/2026,FGN Stamp Duty//307510463////4772285//DEWLL IN...,NaN,-50.00,25584353.09
3,01/07/2026,TRF TO COBITA INVEST (NIG) LTD//Cargo Clearanc...,NaN,-8000000.00,17584353.09
4,01/07/2026,FGN Stamp Duty//TRF TO COBITA INVEST (NIG) LTD...,NaN,-50.00,17584303.09
...,...,...,...,...,...
539,01/08/2026,FGN Stamp Duty//1785602300390/CIB//NIP TFR TO ...,NaN,-50.00,1921005.05
540,01/08/2026,1785611202141/CIB//NIP TFR TO DANCO PETROLEUM ...,NaN,-85000.00,1836005.05
541,01/08/2026,NIP CHARGE + VAT,NaN,-53.75,1835951.30
542,01/08/2026,FGN Stamp Duty//1785611202141/CIB//NIP TFR TO ...,NaN,-50.00,1835901.30
543,NaN,Closing Balance,NaN,NaN,1835901.30

In [ ]:
import numpy as np

#Clean formatting issues before conversion
# Remove commas, currency symbols (₦, $, etc.), and spaces
df["WITHDRAWALS"] = df["WITHDRAWALS"].astype(str).str.replace(",", "", regex=False)
df["WITHDRAWALS"] = df["WITHDRAWALS"].str.replace("₦", "", regex=False).str.strip()
df["DEPOSITS"] = df["DEPOSITS"].astype(str).str.replace(",", "", regex=False)
df["DEPOSITS"] = df["DEPOSITS"].str.replace("₦", "", regex=False).str.strip()

In [ ]:
# Convert DEBIT and CREDIT to numeric (handles text like "0.00" or blanks)
df["WITHDRAWALS"] = pd.to_numeric(df["WITHDRAWALS"], errors="coerce")
df["DEPOSITS"] = pd.to_numeric(df["DEPOSITS"], errors="coerce")

In [ ]:
# Replace 0.00 with NaN
df["WITHDRAWALS"] = df["WITHDRAWALS"].replace(0.00, np.nan)
df["DEPOSITS"] = df["DEPOSITS"].replace(0.00, np.nan)

In [ ]:
df

,DATE,DESCRIPTION,DEPOSITS,WITHDRAWALS,BALANCE
0,NaN,Opening Balance,28097710.09,NaN,28097710.09
1,01/07/2026,307510463////4772285//DEWLL INTERNATIONAL LOGI...,NaN,-2513307.00,25584403.09
2,01/07/2026,FGN Stamp Duty//307510463////4772285//DEWLL IN...,NaN,-50.00,25584353.09
3,01/07/2026,TRF TO COBITA INVEST (NIG) LTD//Cargo Clearanc...,NaN,-8000000.00,17584353.09
4,01/07/2026,FGN Stamp Duty//TRF TO COBITA INVEST (NIG) LTD...,NaN,-50.00,17584303.09
...,...,...,...,...,...
539,01/08/2026,FGN Stamp Duty//1785602300390/CIB//NIP TFR TO ...,NaN,-50.00,1921005.05
540,01/08/2026,1785611202141/CIB//NIP TFR TO DANCO PETROLEUM ...,NaN,-85000.00,1836005.05
541,01/08/2026,NIP CHARGE + VAT,NaN,-53.75,1835951.30
542,01/08/2026,FGN Stamp Duty//1785611202141/CIB//NIP TFR TO ...,NaN,-50.00,1835901.30
543,NaN,Closing Balance,NaN,NaN,1835901.30

In [ ]:
from ast import keyword
def classify_transaction(DESCRIPTION, DEPOSITS, WITHDRAWALS):
    desc = str(DESCRIPTION).upper()

 # --- CREDIT SIDE ---
    if pd.notna(DEPOSITS) and DEPOSITS > 0:
        if any(keyword in desc for keyword in ["LEKKI SEAPORT", "LEKKI PORT"
        ]):
            return "Lekki Port C"
        elif "FINCRA TECHNOLOGIES LIMITED" in desc:
            return "Fincra Technologies Limited"
        elif "DEWLL INERNATIONAL" in desc or  "DEWLL INTERNATIONAL LOGISTICS LTD" in desc:
            return "DEWLL INTERNATIONAL C"
        elif "ADVANCE PAYMENT FOR CUSTOMS CLEARANCE" in desc or "XCMG" in desc:
            return "Advance Payment XCMG"
        else:
            return "Other Credit"

    # --- DEBIT SIDE ---
    if pd.notna(WITHDRAWALS) and WITHDRAWALS < 0:
        if any(keyword in desc for keyword in [
            "BANK_CHARGES", "BANK CHARGES",  "PP_FEE", "FGN STAMP DUTY", "TRSF LEVY", "SMS ALERT", "TRANSFER LEVY",
             "UNDEBITED FEES", "ONLINE PAYMENT FEE"," + VAT", "VAT ON COMMISSION","CHARGE"
        ]):
            return "Charges"
        elif "LEKKI SEAPORT" in desc or "LEKKI PORT" in desc:
            return "Lekki Seaport"
        elif "WEST MERCEDONIA NIG LIMITED" in desc:
            return "West Mercedonia"
        elif "11PLC WAREHOUSE ROAD APAPA" in desc:
            return "11 PLC"
        elif " SIFEM GLOBAL RESOURCES" in desc or "SIFEM GLOBAL RESOURCES - SGR"in desc or "SIFEM GLOBAL RESOURCES - SGR 29" in desc or "SIFEM GLOBAL RESOURCES" in desc:
            return "SIFEM Global Services"
        elif "ABAHAM ENERGY LIMITED" in desc:
            return "Abaham Energy Limited"
        elif "CARRY TRANSPORTATION NIG LTD" in desc:
            return "Carry Transportation Nig LTD"
        elif "DEWLL INTERNATIONAL LOGISTICS LTD" in desc:
            return "Dewll International"
        elif "AFRICA GLO LOG  TRAS" in desc:
            return "Africa Glo Trans"
        elif "SHAFA LIMITED" in desc:
            return "Shafa LTD"
        elif "ROLEZ" in desc:
            return "Rolez"
        elif "OWOLE SALARY" in desc or "OWOLE FLORENCE" in desc:
            return "Owole"
        elif "NATIONAL SINGLE WINDOW" in desc:
            return "Single Window"
        elif "COSCO SHIPPING" in desc or "COSCO SHIPPING LINES (NIGERIA) CO" in desc or "COSCO SHIPPING LINES  NIGERIA  CO." in desc:
            return "Cosco Shipping"
        elif "APM TERMINALS" in desc or "APMT" in desc:
            return "APMT"
        elif "INTB/S E S LTD" in desc:
            return "NTB/SES LTD"
        elif "DANCO PETROLEUM" in desc or "DANCO PETROLEUM LIMITED" in desc or "DANCO PETROLEUM LIMITED" in desc or "DANCO PET" in desc:
            return "Danco Petroleum"
        elif "CARTRIDGE" in desc:
            return "Cartridge"
        elif "OSONOCHI MARKETING" in desc:
            return "Osonoch Marketing"
        elif "BRAVE WAVES" in desc:
            return "Brave Waves"
        elif "COBITA INVEST" in desc:
            return "Cobita"
        elif "QUANLEE OVERSEAS WAREHOUSE" in desc:
            return "QUANLEE OVERSEAS WAREHOUSE"
        elif "DAVID OBATARE" in desc:
            return "David Obatare"
        elif "TRANSFER" in desc or "TRF TO" in desc or "TFR TO" in desc:
            return "Transfer"
        elif "MAINTENANCE FEE" in desc or "ACCOUNT MAINTENNACE" in desc:
            return "Account Maintenance"
        else:
            return "Other Debit"

    # If both columns are NaN or 0
    else:
        return "Uncategorized"

In [ ]:
df["Category"] = df.apply(lambda x: classify_transaction(x["DESCRIPTION"], x["DEPOSITS"],x["WITHDRAWALS"]), axis=1)

In [ ]:
df

,DATE,DESCRIPTION,DEPOSITS,WITHDRAWALS,BALANCE,Category
0,NaN,Opening Balance,28097710.09,NaN,28097710.09,Other Credit
1,01/07/2026,307510463////4772285//DEWLL INTERNATIONAL LOGI...,NaN,-2513307.00,25584403.09,Dewll International
2,01/07/2026,FGN Stamp Duty//307510463////4772285//DEWLL IN...,NaN,-50.00,25584353.09,Charges
3,01/07/2026,TRF TO COBITA INVEST (NIG) LTD//Cargo Clearanc...,NaN,-8000000.00,17584353.09,Cobita
4,01/07/2026,FGN Stamp Duty//TRF TO COBITA INVEST (NIG) LTD...,NaN,-50.00,17584303.09,Charges
...,...,...,...,...,...,...
539,01/08/2026,FGN Stamp Duty//1785602300390/CIB//NIP TFR TO ...,NaN,-50.00,1921005.05,Charges
540,01/08/2026,1785611202141/CIB//NIP TFR TO DANCO PETROLEUM ...,NaN,-85000.00,1836005.05,Danco Petroleum
541,01/08/2026,NIP CHARGE + VAT,NaN,-53.75,1835951.30,Charges
542,01/08/2026,FGN Stamp Duty//1785611202141/CIB//NIP TFR TO ...,NaN,-50.00,1835901.30,Charges
543,NaN,Closing Balance,NaN,NaN,1835901.30,Uncategorized

In [ ]:
Other_Debit =df[df["Category"] =="Other Debit"]

In [ ]:
df_new=Other_Debit

In [ ]:
df_new

,DATE,DESCRIPTION,DEPOSITS,WITHDRAWALS,BALANCE,Category
52,06/07/2026,NPS CR/INTB/MEDITERRANEAN SHIPPING COY NIG/GTB...,NaN,-299545.00,27361894.29,Other Debit
57,06/07/2026,NIP CR/INTB/HASSAN ABDULLAHI/UBA / lin,NaN,-6000.00,26954054.54,Other Debit
59,06/07/2026,NIP CR/INTB/SHISU MUSTAPHA/ABN / lin,NaN,-31000.00,26923027.66,Other Debit
92,13/07/2026,eBillsPay DR/WEST AFRICA CONTAINER TERMINAL/GTB,NaN,-11348660.00,15304686.69,Other Debit
100,14/07/2026,NIP CR/INTB/SAHWAAD VENTURES/FBNMM/ lin,NaN,-48000.00,4357577.31,Other Debit
106,14/07/2026,CIP/CR/INTB/ABUBAKAR JELANI/OPAY /00001526071...,NaN,-16000.00,2631396.68,Other Debit
109,14/07/2026,CIP/CR/INTB/KABIRU ABDULLAHI/OPAY /00001526071...,NaN,-232500.00,2398819.80,Other Debit
112,14/07/2026,CIP/CR/INTB/JOHN CHUKWUEMEKA EMMANUEL/OPAY /00...,NaN,-10000.00,2388716.05,Other Debit
117,14/07/2026,CIP/CR/INTB/OMIRINYA THOMAS/FCMB /000015260714...,NaN,-500000.00,1823286.67,Other Debit
137,15/07/2026,NIP CR/INTB/MAHMUD YAKUBU/UBA / lin,NaN,-5000.00,113794.78,Other Debit
140,16/07/2026,PTG-5125571829806893-GlobalPay Bank Payment,NaN,-9752400.00,20361384.03,Other Debit
145,16/07/2026,NIP CR/INTB/LIN CHANGCONG/ABN / daily life fee,NaN,-2000000.00,17861230.28,Other Debit
175,17/07/2026,NIP CR/INTB/JELANI ABUBAKAR/PBNL / lin,NaN,-2460622.00,12193018.87,Other Debit
192,18/07/2026,NIP CR/INTB/HASSAN ABDULLAHI/UBA /lin,NaN,-29000.00,8235450.12,Other Debit
195,18/07/2026,NIP CR/INTB/MAHMUD YAKUBU/UBA /lin,NaN,-29000.00,8206373.24,Other Debit
198,18/07/2026,NIP CR/INTB/ABUBAKAR ILIYASU/UBA /lin,NaN,-10000.00,8196296.36,Other Debit
210,18/07/2026,NIP CR/INTB/OLAWALE BABATUNDE OJOAYOADE/OPAY /lin,NaN,-60000.00,8057365.73,Other Debit
227,19/07/2026,CIP/CR/INTB/ADEKUNLE SUNDAY AYODELE/OPAY /0000...,NaN,-9000.00,7245263.84,Other Debit
229,19/07/2026,PTG-5248808334377782-GlobalPay Bank Payment,NaN,-4388580.00,2856656.96,Other Debit
231,19/07/2026,CIP/CR/INTB/AMINU ALI/OPAY /00001526071916495...,NaN,-29000.00,2827606.96,Other Debit
234,19/07/2026,NIP CR/INTB/Federal Inland Revenue Serv FIRS/I...,NaN,-123241.12,2704288.96,Other Debit
238,20/07/2026,FGN IMPORT WEB PTY/14990,NaN,-9464939.17,2239246.04,Other Debit
271,23/07/2026,AREWA HARVEST AGRO/GLOBU,NaN,-7800000.00,11333209.36,Other Debit
283,24/07/2026,JOSEPDAM PORT SERVICES JPS NIGERIA LTD/UBA,NaN,-521457.97,10747740.12,Other Debit
289,24/07/2026,TO JOSEPDAM PORT SERVICES JPS NIGERIA LTD/UBA,NaN,-1255242.22,7992453.43,Other Debit
302,25/07/2026,TO SHISU MUSTAPHA/ABN,NaN,-20000.00,7932015.04,Other Debit
314,25/07/2026,NIP CR/INTB/HASSAN ABDULLAHI/UBA / lin,NaN,-4500.00,7797467.23,Other Debit
325,27/07/2026,NPS CR/INTB/SQUAD CMA CGM NIGERIA SHIPPING LT...,NaN,-190550.76,2652594.47,Other Debit
328,27/07/2026,NPS CR/INTB/SQUAD CMA CGM NIGERIA SHIPPING LT...,NaN,-730623.75,1921866.97,Other Debit
334,28/07/2026,CIP/CR/INTB/OLAWALE BABATUNDE OJOAYOADE/OPAY /...,NaN,-25000.00,1861161.34,Other Debit
350,29/07/2026,NPS CR/INTB/ALRAINE SHIPPING AGENCIES NIG /GTB...,NaN,-193550.00,8718628.74,Other Debit
353,29/07/2026,CIP/CR/INTB/AMINU ALI/OPAY /00001526072911523...,NaN,-8000.00,8710524.99,Other Debit
386,29/07/2026,NIP CR/INTB/LIN CHANGCONG/ABN / lin,NaN,-1000000.00,55849309.22,Other Debit
514,31/07/2026,NIP CR/INTB/TILACO DYNAMIC SERVICES/WBP / 175...,NaN,-7008750.00,3003018.38,Other Debit
534,01/08/2026,NIP CR/INTB/OLAWALE BABATUNDE OJOAYOADE/OPAY /...,NaN,-60000.00,2006212.55,Other Debit

In [ ]:
df[df["Category"] == "Other Credit"]

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,DATE,DESCRIPTION,DEPOSITS,WITHDRAWALS,BALANCE,Category
0,NaN,Opening Balance,28097710.09,NaN,28097710.09,Other Credit
207,18/07/2026,***RSVL NIP CHARGE + VAT,53.75,NaN,8057315.73,Other Credit
208,18/07/2026,***RSVL NIP CR/INTB/OLAWALE OJOAYOADE/ROLEZ/lin,60000.00,NaN,8117315.73,Other Credit
209,18/07/2026,***RSVL FGN Stamp Duty//NIP CR/INTB/OLAWALE OJ...,50.00,NaN,8117365.73,Other Credit
481,31/07/2026,***RSVL NIP CHARGE + VAT,53.75,NaN,9889472.88,Other Credit
482,31/07/2026,***RSVL FGN Stamp Duty//1785496299084/CIB//NIP...,50.00,NaN,9889522.88,Other Credit
483,31/07/2026,"***RSVL 1785496299084/CIB//NIP TFR TO SAMINU, ...",160000.00,NaN,10049522.88,Other Credit

In [ ]:
output_path = "/content/drive/MyDrive/pluralcode data science/Zenith_DEWll_PEJUclassified.xlsx"

with pd.ExcelWriter(output_path, engine='openpyxl') as writer:

    # Full dataset (keep Balance)
    df.to_excel(writer, sheet_name="Full Dataset", index=False)

    # Category sheets (remove Balance)
    for category, group in df.groupby("Category"):

       # Remove Balance column for category sheets
        group_no_balance = group.drop(columns=["Balance"], errors="ignore")

        # Clean sheet name
        safe_name = str(category)[:30].replace("/", "_")
        group.to_excel(writer, sheet_name=safe_name, index=False)

print("✅ Excel file created successfully at:", output_path)

✅ Excel file created successfully at: /content/drive/MyDrive/pluralcode data science/Zenith_DEWll_PEJUclassified.xlsx